# Define a 'Persistent Volume Claim'(PVC) for Mysql Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc   # Name of PVC essential for identifying the storage data
spec:
  accessModes:
    - ReadWriteOnce   # This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 1Gi    # This will tell kubernetes about the amount of space we are trying to claim.

---     # you must add '---' if you want to define multiple config objects in one yaml file

# Configure 'Deployment' of mysql server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD         # this is an environment variable that must be defined when creating a container from a mysql docker image
              value: root
            - name: MYSQL_DATABASE
              value: customer_service_db
          volumeMounts:
            - name: mysql-persistent-storage    # Mounting volume obtained from Persistent Volume Claim
              mountPath: /var/lib/mysql         # This is the path in the container on which the mounting will take place.
      volumes:
        - name: mysql-persistent-storage # Obtaining 'volume' from PVC
          persistentVolumeClaim:
            claimName: mysql-pvc

---

# Define a 'Service' To Expose mysql to Other Services
apiVersion: v1
kind: Service
metadata:
  name: mysql-service   # DNS name (endpoint). This is the endpoint that we use to access the mysql server. mysql -h mysql-service -u root -p
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None  # We have defined DNS endpoint above (metadata:name mysql-service), Thus ClusterIP is not needed


