apiVersion: v1
kind: ConfigMap                  # defines the type of the kubernetes object
metadata:
  name: customer-k8s-config      # defines the name for the config map
data:                            # defines the key-value pairs
  dbName: customer_service_db    # key - dbName, value - customer_service_db
